pgsql:
  image: postgres:9.4
  volumes_from:
    - geocat_pgdata
  extends:
    file: docker-compose.private.yml
    service: passwords

backend:
  build: backend

  links:
    - pgsql:pgsql

  environment:
    - PORT=3000
    - POSTGRES_HOST=pgsql
    - POSTGRES_DB=geocat

  command: nodemon -L
  #command: bin/infinitystart

  extends:
    file: docker-compose.private.yml
    service: passwords

  # DEV
  ports:
    - 3000:3000
  
  volumes:
    - ./backend:/usr/src/app
