pgsql:
  restart: always
  image: postgres:9.4
  volumes_from:
    - geocat_pgdata
  extends:
    file: docker-compose.private.yml
    service: passwords

backend:
  restart: always
  build: backend
  links:
    - pgsql:pgsql
  environment:
    - PORT=3000
    - POSTGRES_HOST=pgsql
    - POSTGRES_DB=geocat

  extends:
    file: docker-compose.private.yml
    service: passwords
